#!/bin/sh
[ "$1" = --down ] || exit 1
# 防止重复启动
LOCK=/var/lock/adblock.lock
[ -f $LOCK ] && exit 1
touch $LOCK

A=0
B=/tmp/adblock
C=/tmp/adupdate.log
D="date +'%Y-%m-%d %H:%M:%S'"
E="curl -Lfso"
F="Download Adblock Plus Rules"
G="Download Subscribe Rules"

if [ "$2" = 1 ];then
	mkdir -p $B
	echo "`eval $D` [$F]" > $C
	while ! $E $B/adblock.conf https://cdn.jsdelivr.net/gh/small-5/ad-rules/dnsmasq.adblock;do
		sleep 2
	done
	echo "`eval $D` [$F Successful]" >> $C
	for i in $(cat /etc/adblock/white.list);do sed -i -e "/\/$i\//d" -e "/\.$i\//d" $B/adblock.conf;done
fi

if [ "$3" = 1 -a $A != 1 ];then
	echo "`eval $D` [$G]" >> $C
	/usr/share/adblock/adblock addown >> $C
fi

[ $A = 1 ] || (echo "`eval $D` [Start Adblock Plus+]" >> $C;echo `eval $D` > $B/adblock.updated)
rm -f $LOCK
/etc/init.d/adblock start &
