#!/bin/sh
if [ "$ACTION" = ifup ];then
	if uci -q get bypass.@global[0].global_server >/dev/null;then
		if ipset list ssr_plus_all >/dev/null 2>&1;then
			ipset -F ssr_plus_all
			for i in $(ip -4 add show | grep -v $(uci -P /tmp/state get network.wan.ifname) | grep inet | grep -v 127.0.0.1 | awk '{print$2}');do
				ipset -! add ssr_plus_all $i
			done
		fi
		if pidof smartdns >/dev/null;then
			killall -q -9 smartdns
			$(which smartdns) -c /var/etc/smartdns/smartdns.conf
		fi
	fi
fi
