#!/bin/sh 

[ -e "/etc/config/ucitrack" ] && {
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@aliddns[-1]
	add ucitrack aliddns
	set ucitrack.@aliddns[-1].init=aliddns
	commit ucitrack
EOF
}

rm -rf /tmp/luci-modulecache /tmp/luci-indexcache
exit 0

