#!/bin/sh /etc/rc.common
# Created By immortalwrt
# https://github.com/immortalwrt

START=99
STOP=10

PROG=/usr/bin/ssocksd

load_config() {
	enable="$(uci get ssocksd.@ssocksd[0].enable)"
	bind_addr="$(uci get ssocksd.@ssocksd[0].bind_addr)"
	listen_port="$(uci get ssocksd.@ssocksd[0].listen_port)"
	username="$(uci get ssocksd.@ssocksd[0].username)"
	password="$(uci get ssocksd.@ssocksd[0].password)"
}

lan_config() {
	lan_addr="$(uci get network.lan.ipaddr)"
}

start()
{
	load_config
	lan_config

	stop

	[ "$enable" = "1" ] || return 1

	mkdir -p "/tmp/"
	mkdir -p "/var/etc/"

	[ "${bind_addr}" == "lan" ] && bind_address="${lan_addr}" || bind_address="0.0.0.0"

	if [ -n "${username}" ] && [ -n "${password}" ]; then
		rm -f /etc/config/ssocksd-authorization
		echo "${username}:${password}" > /etc/config/ssocksd-authorization
		auth_arg="--auth /etc/config/ssocksd-authorization"
	fi

	/usr/bin/ssocksd --port "${listen_port}" --bind "${bind_address}" ${auth_arg} >/dev/null 2>&1 &

	iptables -I INPUT -p tcp --dport "${listen_port}" -j ACCEPT
	cat <<-EOF > "/var/etc/ssocksd.include"
iptables -I INPUT -p tcp --dport "${listen_port}" -j ACCEPT
	EOF
}

stop()
{
	killall -9 "$PROG" >/dev/null 2>&1
	rm -f "/etc/config/ssocksd-authorization"
	rm -f "/var/etc/ssocksd.include"
}
