#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org
# Copyright (C) 2020.2.14 NiHaoDD.Com

START=70
USE_PROCD=1
LOGFILE="/tmp/npc.log"
conf="/etc/conf/npsvip.conf"

header() {
	config_get enabled $1 enabled
}

start_service() {
	config_load npsvip
	config_foreach header

	if [ "$enabled" = "1" ];then
	procd_open_instance
    	procd_set_param command /usr/bin/npsvip -config=$conf
    	procd_set_param respawn
    	procd_set_param stdout 1
    	procd_set_param stderr 1
    	procd_close_instance
	fi
}

triggers_service() {
	procd_add_reload_trigger "npsvip"
}

restart_service() {
	stop
	start
}