#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org
# Copyright (C) 2020.2.14 NiHaoDD.Com

START=70
USE_PROCD=1
CONF="/etc/nihaodd/npc/npsvip.conf"

header() {
	config_get enabled $1 enabled

	if [ -z "$(grep '/etc/nihaodd/' /etc/sysupgrade.conf)" ];then
		echo "/etc/nihaodd/" >> /etc/sysupgrade.conf
	fi
}

start_service() {
	config_load npsvip
	config_foreach header

	if [ "$enabled" = "1" ];then
		checknpc
		procd_open_instance
    	procd_set_param command /usr/bin/npsvip
    	procd_append_param command -config=$CONF
    	procd_set_param respawn
    	procd_set_param stdout 1
    	procd_set_param stderr 1
    	procd_close_instance
	fi
}

service_triggers() {
	procd_add_reload_trigger "npsvip"
}

service_relod() {
	stop
	start
}

service_stop() {
	stop
}

service_restart() {
	stop
	start
}
