#!/bin/sh /etc/rc.common
# Author=wulishui , 20200908-0915 ; <wulishui@gmail.com>

START=55


start() {
sumenabled=$(cat /etc/config/rebootschedule 2>/dev/null|grep -c 'option enable .1.')
if [ "$sumenabled" -gt 0 ]; then
[ -s /etc/crontabs/root ] || mcronrst=1
sed -i '/rebootschedule/d' /etc/crontabs/root 2>/dev/null
sum=$(cat /etc/config/rebootschedule 2>/dev/null|grep -c 'config crontab')
for i in $(seq 0 $((sum-1)))
do
enable=`uci get rebootschedule.@crontab[$i].enable 2>/dev/null`
if [ "$enable" == 1 ]; then
month=`uci get rebootschedule.@crontab[$i].month 2>/dev/null` || month="*"
day=`uci get rebootschedule.@crontab[$i].day 2>/dev/null` || day="*"
week=`uci get rebootschedule.@crontab[$i].week 2>/dev/null` || week="*"
#[ ! "$day" = "*" ] && week="*"
hour=`uci get rebootschedule.@crontab[$i].hour 2>/dev/null` || hour="*" ; [ "$hour" = "0" ] && hour="00"
minute=`uci get rebootschedule.@crontab[$i].minute 2>/dev/null` || minute="00" ; [ "$minute" = "0" ] && minute="00"
command=`uci get rebootschedule.@crontab[$i].command 2>/dev/null` || command="echo "Reboot schedule tested.""
echo "$minute $hour $day $month $week $command    #By rebootschedule" >> /etc/crontabs/root
fi
done
[ "$mcronrst" == 1 ] && /etc/init.d/cron restart
fi
}

stop() {
sed -i '/rebootschedule/d' /etc/crontabs/root 2>/dev/nul
}

