# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2017-2023 <name>

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for qBittorrent
LUCI_DEPENDS:=+qbittorrent
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
