#!/bin/sh
# 
# Copyright 2018-2023 Nick Peng <zxlhhyccc@gmail.com>
# Licensed to the public under the GPL V3 License.

action=$1
shift

audit_log_file="$(uci -q get smartdns.@smartdns[0].audit_log_file)"
audit_list_file="${log_file:-/var/log/smartdns/smartdns-audit.log}"

case "$action" in
      tail)
            if [ ! -e "$audit_list_file" ]; then
                  echo "Log file does not exist."
            fi
            # read log
            tail -n 5000 "$audit_list_file"
            ;;
      clear_log)
            # clear log
            > $audit_list_file
            ;;
esac
