#!/bin/sh
touch /etc/config/arpbind

[ -e "/etc/config/ucitrack" ] && {
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@arpbind[-1]
	add ucitrack arpbind
	set ucitrack.@arpbind[-1].init=arpbind
	commit ucitrack
EOF
}

rm -f /tmp/luci-indexcache
exit 0
