#!/bin/sh 

uci -q batch <<-EOF >/dev/null
          delete ucitrack.@verysync[-1]
          add ucitrack verysync
          set ucitrack.@verysync[-1].init=verysync
          commit ucitrack
EOF

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
