#
# Copyright (C) 2018 By-Ameng Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=luci-app-control-guest-wifi
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_VERSION:=1.1
PKG_RELEASE:=20200924

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
