#!/bin/sh /etc/rc.common
# verysync Script VER 0.10 for openwrt  by Rapistor(明月永在)

START=99

PROG="/usr/bin/verysync.init"

load_config() {
enabled=$(uci get verysync.setting.enable)
delay=$(uci get verysync.setting.delay)
}

start() {
	load_config
	[ "$enabled" = "1" ] && $PROG start
}

stop() {
	load_config
	[ "$enabled" = "0" ] && $PROG stop
}

restart() {
	stop
	sleep 2
	start
}

boot() {
	[ "$enabled" = "1" ] && {
		sleep $delay
		start
	}
}
