#!/bin/sh

uci -q batch <<-EOF >/dev/null
	[ -e "/etc/config/ucitrack" ] && {
	delete ucitrack.@zerotier[-1]
	commit ucitrack
	}

	delete firewall.zerotier
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0
