#!/bin/sh

[ -z "$DEVICENAME" ] && exit 0
echo "$DEVICENAME" | grep -Eq "^zt" || exit 0

logger -t zerotier "Hotplug event: ACTION=$ACTION INTERFACE=$INTERFACE DEVICENAME=$DEVICENAME"

lockfile="/var/lock/zerotier-nat.lock"

case "$ACTION" in
	add)
		logger -t zerotier "Hotplug: Interface $DEVICENAME added"

		(
			flock -n 200 || exit 1
			sleep 1
			zerotier-nat start "$DEVICENAME" >/dev/null 2>&1
			logger -t zerotier "zerotier-nat start $DEVICENAME done"
		) 200>"$lockfile" &
		;;

	remove)
		logger -t zerotier "Hotplug: Interface $DEVICENAME removed"

		(
			flock -n 200 || exit 1
			zerotier-nat stop >/dev/null 2>&1
			logger -t zerotier "zerotier-nat stop done"
		) 200>"$lockfile"
		;;
esac

