# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-cowb-timecontrol
PKG_VERSION:=v22.1.9-1038-1
PKG_RELEASE:=1
LUCI_TITLE:=LuCI support for TimeControl
LUCI_DEPENDS:=+libc +iptables-mod-filter +kmod-ipt-filter +bash
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature


