#!/bin/sh /etc/rc.common
# verysync Script VER 0.10 for openwrt  by Rapistor(明月永在)

START=99

enabled=$(uci get verysync.setting.enable)
delay=$(uci get verysync.setting.delay)

start() {
	[ "$enabled" = "1" ] && /usr/bin/verysync.init start
}

stop() {
	[ "$enabled" = "0" ] && /usr/bin/verysync.init stop
}

restart() {
	stop        
	sleep 2     
	start       
}   

boot() {
	[ "$enabled" = "1" ] && {
		sleep $delay
		start
	}
}
