#!/bin/sh

[ -e "/etc/config/ucitrack" ] && {
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@filebrowser[-1]
	add ucitrack filebrowser
	set ucitrack.@filebrowser[-1].init=filebrowser
	commit ucitrack
EOF
}

rm -f /tmp/luci-indexcache
exit 0
