#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org
# Copyright (C) 2020.2.14 NiHaoDD.Com

START=50
USE_PROCD=1

LOGFILE="/tmp/nps.log"
tmpconf="/etc/config/nps"

nps_header() {
	local enabled server_addr server_port protocol vkey compress crypt log_level

	# ln -sf /usr/bin/conf /root/conf
	config_get enabled $1 enabled

	Enabled=$enabled
}

nps_write_bool() {
	local opt="$1"
	local config="$2"
	local val

	config_get_bool val $config "$opt"
	if [ "$val" -eq 0 ]; then
		echo "${opt}=false" >> $tmpconf
	else
		echo "${opt}=true" >> $tmpconf
	fi
}

start_service() {
	config_load nps
	config_foreach nps_header nps

	if [ "$Enabled" = "1" ];then
		logger -t FRPC 'Starting Nps service'
		procd_open_instance
    		procd_set_param command /usr/bin/nps
    		procd_set_param respawn
    		procd_set_param stdout 1
    		procd_set_param stderr 1
    		procd_close_instance
	fi
}

service_triggers() {
        procd_add_reload_trigger "nps"
}

service_restart() {
        stop
        start
}
