#!/bin/sh
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@bypass[-1]
	add ucitrack bypass
	set ucitrack.@bypass[-1].init=bypass
	commit ucitrack
	delete firewall.bypass
	set firewall.bypass=include
	set firewall.bypass.type=script
	set firewall.bypass.path=/var/etc/bypass.include
	set firewall.bypass.reload=1
	commit firewall
EOF
cp -n /etc/config/shadowsocksr /etc/config/bypass 2>/dev/null
sed -i 's/vmess_id/uuid/g' /etc/config/bypass 2>/dev/null
chmod 755 /etc/init.d/bypass /usr/share/bypass/* >/dev/null 2>&1
/etc/init.d/bypass enable >/dev/null 2>&1
rm -rf /tmp/luci-modulecache /tmp/luci-indexcache*
killall -HUP rpcd 2>/dev/null
exit 0
