#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@AdGuard-Home[-1]
	add ucitrack AdGuard-Home
	set ucitrack.@AdGuard-Home[-1].exec='/etc/init.d/AdGuard-Home start'
	commit ucitrack
EOF
        echo "/usr/bin/AdGuardHome.yaml" >> /etc/sysupgrade.conf
        echo "/usr/bin/data/filters/" >> /etc/sysupgrade.conf

rm -f /tmp/luci-indexcache
exit 0
