#!/bin/sh

if ! uci -q get system.@system[0].zram_size_mb > "/dev/null"; then
	uci -q batch <<-EOF
		set system.@system[0].zram_size_mb="300"
		set system.@system[0].zram_comp_algo="zstd"
		commit system
	EOF
fi

exit 0
