#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2015 OpenWrt.org

START=99

PROG="/usr/bin/amule.init"

load_config() {
enabled=$(uci get amule.main.enabled)
}

start() {
	load_config
	[ "$enabled" = "1" ] && $PROG trace
}

stop() {
	load_config
	[ "$enabled" = "0" ] && $PROG stop
}

restart() {
	stop
	sleep 2
	start
}

boot() {
	[ "$enabled" = "1" ] && {
		start
	}
}

