#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
  AdG=$(uci get verysync.config.enabled 2>/dev/null)
  if [ $AdG -eq 1 ];   then
	rm -f /usr/bin/verysync.old 2>/dev/null
	procd_open_instance
	procd_set_param command verysync -home="$(uci get verysync.config.home)" -gui-address="0.0.0.0:$(uci get verysync.config.port)" -logfile="/var/log/verysync.log" -no-browser
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
  fi
}

service_triggers() {
	procd_add_reload_trigger "verysync"
}

stop_service() {
	kill -9 $(busybox ps -w | grep 'verysync' | grep -v 'grep' | awk '{print $1}') >/dev/null 2>&1
}

restart() {
stop
start
}

