include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for v2rayA
LUCI_DEPENDS:=+v2raya-v5 +lua +libuci-lua
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-v2raya-v5
PKG_VERSION:=1.0
PKG_RELEASE:=2

PKG_MAINTAINER:=zxlhhyccc <zxlhhy@gmail.com>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
