#!/bin/sh

action=$1
shift

log_file="$(uci -q get frps.common.log_file)"
list_file="${log_file:-/var/log/frps.log}"

case "$action" in
	tail)
	# 读取日志
		tail -n 5000 "$list_file"
	;;
	clear_log)
	# 清空日志
		> $list_file
	;;
esac

