#!/bin/sh /etc/rc.common
# Created By immortalwrt
# https://github.com/immortalwrt

START=99

PROG="/usr/bin/ssocksd.init"

load_config() {
enable=$(uci get ssocksd.@ssocksd[0].enable)
}

start() {
	load_config
	[ "$enable" = "1" ] && $PROG start
}

stop() {
	load_config
	[ "$enable" = "0" ] && $PROG stop
}

restart() {
	stop
	sleep 2
	start
}

boot() {
	[ "$enabled" = "1" ] && {
		start
	}
}
