#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

CONF="baidupcs-web"
PROG="/usr/bin/baidupcs-web"

get_config() {
	config_get_bool enabled "$1" 'enabled' '0'
	config_get port "$1" 'port'
	config_get download_dir "$1" 'download_dir'
	config_get max_download_rate "$1" 'max_download_rate' || echo '0'
	config_get max_upload_rate "$1" 'max_upload_rate' || echo '0'
	config_get max_download_load "$1" 'max_download_load' || echo '1'
	config_get max_parallel  "$1" 'max_parallel ' || echo '8'
}

start_service() {
	stop_service
	config_load "$CONF"
	config_foreach get_config "$CONF"

	[ "$enabled" = "1" ] || return 1

	mkdir -p "${download_dir}"

	baidupcs-web config set                         \
	--savedir               "${download_dir}"       \
	--max_download_rate     "${max_download_rate}"  \
	--max_upload_rate       "${max_upload_rate}"    \
	--max_download_load     "${max_download_load}"  \
	--max_parallel          "${max_parallel}"       \
	--max_upload_parallel   "${max_parallel}"       \
	>/dev/null 2>&1

	procd_open_instance "$CONF"
	procd_set_param command "$PROG"
	procd_append_param command web --port "${port}" --access >/dev/null 2>&1 &
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}

reload_service() {
	stop
	start
}

stop_service() {
	killall -3 baidupcs-web >/dev/null 2>&1
}
